### PR TITLE
Add ability to export as HAR File

### PR DESCRIPTION
**Pull request by latacora-tomekr**
This PR adds the export feautre of https://github.com/nccgroup/LoggerPlusPlus/issues/101 according to the [HAR file spec](https://w3c.github.io/web-performance/specs/HAR/Overview.html#sec-object-types-queryString). 

https://github.com/nccgroup/LoggerPlusPlus/commit/efbe7077a1b04945c33e9d34868e9a0a5c8a1906 Creates a HARExporter and serializer that gets added to the current list of exporters.
https://github.com/nccgroup/LoggerPlusPlus/commit/3895efbf8248176cb02907a48a06fad02f2c431a and https://github.com/nccgroup/LoggerPlusPlus/commit/e85db02599c1ff953a6b3263fc9af86f1d7e5a91 are required additions to support the new fields of the HAR file.
https://github.com/nccgroup/LoggerPlusPlus/commit/85a3f4a881cab8c330fb042da0624c33f8604b68 The auto formatter in VS Code ran on a few files 

The [HARSerializer](https://github.com/nccgroup/LoggerPlusPlus/compare/master...latacora-tomekr:har-export?expand=1#diff-dc2a19bb7cc77873833ae0e2e54660db)'s `write` function is one large function which for the most part maps `LogEntry` fields to the HAR file format's JSON fields. As a result, this function is pretty big. If you'd prefer that get split up in any way, let me know and I can make the changes.

A sample HAR file generated by the exporter can be found here: [LoggerPlusPlus.har.txt](https://github.com/nccgroup/LoggerPlusPlus/files/5071139/LoggerPlusPlus.har.txt)

Screen Shot 2020-08-13 at 2 29 30 PM
Screen Shot 2020-08-13 at 2 29 54 PM

Note, this only implements export, import is left as a TODO

### CODE REVIEW

**Comment by CoreyD97** [comment]
Thank you for this PR, I've just had a quick glance over the code and it looks perfect! 
I'll check it out properly to make sure all works as expected and then merge it soon 👍

**Comment by latacora-tomekr** [comment]
Ah I may have found an issue. The spec says:

> A HAR file is REQUIRED to be saved in UTF-8 encoding. Other encodings are forbidden. A reader MUST ignore a byte-order mark if it exists in the file, and a writer MAY emit a byte-order mark in the file.

I believe the default encoder uses unicode. Here is a sample of a multipart file upload parameter:

```
              {
                "name": "upfile",
                "value": "PNG\r\n\u001a\n\u0000\u0000\u0000\rIHDR\u0000\u0000\u0001\u0000 ..."
              },
```

**Comment by latacora-tomekr** [comment]
👋  Checking back in on this to see if you have a recommended way to switch to UTF-8

**Comment by CoreyD97** [comment]
Thanks for the poke on this, I've had a look and it seems to me that it is already formatting the files as UTF-8 as far as I can see. If you're `cat`'ing the file to the terminal you'll probably get some issues, as it'll try to display the characters, but using `less` you'll probably see something similar to the below.

UTF-8 Encoding

Other than that, just one small issue with imported entries having a null request time cannot be exported but I've fixed that :smile:

If you can confirm that the files are indeed UTF-8 encoded on your end I'll go ahead and merge this :+1:

**Comment by latacora-tomekr** [comment]
oh yep, good call! Yea looks good to me then!

**Pull request merged**
